### ISSUE TITLE
Qwiic Fan Controller Firmware Possible Divide-by-Zero Errors

### ISSUE THREAD

**Issue by dlkeng** [sparkfunX/Qwiic_Blower_Fan#4]
In testing the "**Qwiic_Fan_Controller.ino**" firmware, I have observed and run into the following possible divide-by-zero errors:

In function `readTachometer()`:
 - Line 329: If variable `tach` is zero (not likely, but possible)
 - Line 330: If `registerMap[FAN_TACH_DIVIDER]` is zero (possible since is controlled over I2C bus)

In my simulated testing on an Arduino Nano with Arduino 1.8.13, it appears that either of the above cases can crash the firmware or cause other incorrect operations, including infinitely clock-stretching SCL on the I2C bus in response to an I2C bus transaction.

**Comment by NPoole** [comment]
Thanks for sniffing this out, v11 fixes this
